### ISSUE TITLE
deploying to aws

### ISSUE THREAD

**Issue by cordoval** [kevinsimper/cyclesdk#11]
What would be the ideal pro way to deploy this sample project to aws?

I have used terraform for projects and other things but was wondering what your thoughts are.

EDIT: btw are you in Lima? if so get in touch please 💃

**Comment by kevinsimper** [comment]
I use docker and cloud.docker.com to continues deploy the website :) It is pretty easy and it does it on every push to master. Sent you an email.

**Comment by cordoval** [comment]
i replied 👍 i see

**Comment by cordoval** [comment]
i was more thinking on mission control https://github.com/space-race/mission-control
